package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Administradores generated by hbm2java
 */
public class Administradores  implements java.io.Serializable {


     private String telParticular;
     private Usuarios usuarios;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correo;
     private byte[] imagen;
     private Set domicilioAdministradoreses = new HashSet(0);

    public Administradores() {
    }

	
    public Administradores(String telParticular, Usuarios usuarios, String nombre, String apellidoPaterno, String apellidoMaterno) {
        this.telParticular = telParticular;
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
    }
    public Administradores(String telParticular, Usuarios usuarios, String nombre, String apellidoPaterno, String apellidoMaterno, String correo, byte[] imagen, Set domicilioAdministradoreses) {
       this.telParticular = telParticular;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correo = correo;
       this.imagen = imagen;
       this.domicilioAdministradoreses = domicilioAdministradoreses;
    }
   
    public String getTelParticular() {
        return this.telParticular;
    }
    
    public void setTelParticular(String telParticular) {
        this.telParticular = telParticular;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set getDomicilioAdministradoreses() {
        return this.domicilioAdministradoreses;
    }
    
    public void setDomicilioAdministradoreses(Set domicilioAdministradoreses) {
        this.domicilioAdministradoreses = domicilioAdministradoreses;
    }




}


