package com.hibernate.model;
// Generated 22-may-2015 20:27:16 by Hibernate Tools 4.3.1



/**
 * Cirujias generated by hbm2java
 */
public class Cirujias  implements java.io.Serializable {


     private Long id;
     private DatosClinicos datosClinicos;
     private String tipoCirujia;
     private Integer noCirujia;

    public Cirujias() {
    }

	
    public Cirujias(DatosClinicos datosClinicos) {
        this.datosClinicos = datosClinicos;
    }
    public Cirujias(DatosClinicos datosClinicos, String tipoCirujia, Integer noCirujia) {
       this.datosClinicos = datosClinicos;
       this.tipoCirujia = tipoCirujia;
       this.noCirujia = noCirujia;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public DatosClinicos getDatosClinicos() {
        return this.datosClinicos;
    }
    
    public void setDatosClinicos(DatosClinicos datosClinicos) {
        this.datosClinicos = datosClinicos;
    }
    public String getTipoCirujia() {
        return this.tipoCirujia;
    }
    
    public void setTipoCirujia(String tipoCirujia) {
        this.tipoCirujia = tipoCirujia;
    }
    public Integer getNoCirujia() {
        return this.noCirujia;
    }
    
    public void setNoCirujia(Integer noCirujia) {
        this.noCirujia = noCirujia;
    }




}


