package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1



/**
 * Cirugias generated by hbm2java
 */
public class Cirugias  implements java.io.Serializable {


     private Long id;
     private DatosClinicos datosClinicos;
     private String tipoCirugia;
     private Integer noCirugia;

    public Cirugias() {
    }

	
    public Cirugias(DatosClinicos datosClinicos) {
        this.datosClinicos = datosClinicos;
    }
    public Cirugias(DatosClinicos datosClinicos, String tipoCirugia, Integer noCirugia) {
       this.datosClinicos = datosClinicos;
       this.tipoCirugia = tipoCirugia;
       this.noCirugia = noCirugia;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public DatosClinicos getDatosClinicos() {
        return this.datosClinicos;
    }
    
    public void setDatosClinicos(DatosClinicos datosClinicos) {
        this.datosClinicos = datosClinicos;
    }
    public String getTipoCirugia() {
        return this.tipoCirugia;
    }
    
    public void setTipoCirugia(String tipoCirugia) {
        this.tipoCirugia = tipoCirugia;
    }
    public Integer getNoCirugia() {
        return this.noCirugia;
    }
    
    public void setNoCirugia(Integer noCirugia) {
        this.noCirugia = noCirugia;
    }




}


