package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DatosClinicos generated by hbm2java
 */
public class DatosClinicos  implements java.io.Serializable {


     private long noHistorial;
     private Pacientes pacientes;
     private boolean usoDrogas;
     private boolean usoAlcohol;
     private boolean fumador;
     private Set cirugiases = new HashSet(0);
     private Set enfermedadesCronicases = new HashSet(0);
     private Set alergiases = new HashSet(0);
     private Set medicacions = new HashSet(0);
     private Set discapacidadeses = new HashSet(0);

    public DatosClinicos() {
    }

	
    public DatosClinicos(long noHistorial, Pacientes pacientes, boolean usoDrogas, boolean usoAlcohol, boolean fumador) {
        this.noHistorial = noHistorial;
        this.pacientes = pacientes;
        this.usoDrogas = usoDrogas;
        this.usoAlcohol = usoAlcohol;
        this.fumador = fumador;
    }
    public DatosClinicos(long noHistorial, Pacientes pacientes, boolean usoDrogas, boolean usoAlcohol, boolean fumador, Set cirugiases, Set enfermedadesCronicases, Set alergiases, Set medicacions, Set discapacidadeses) {
       this.noHistorial = noHistorial;
       this.pacientes = pacientes;
       this.usoDrogas = usoDrogas;
       this.usoAlcohol = usoAlcohol;
       this.fumador = fumador;
       this.cirugiases = cirugiases;
       this.enfermedadesCronicases = enfermedadesCronicases;
       this.alergiases = alergiases;
       this.medicacions = medicacions;
       this.discapacidadeses = discapacidadeses;
    }
   
    public long getNoHistorial() {
        return this.noHistorial;
    }
    
    public void setNoHistorial(long noHistorial) {
        this.noHistorial = noHistorial;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public boolean isUsoDrogas() {
        return this.usoDrogas;
    }
    
    public void setUsoDrogas(boolean usoDrogas) {
        this.usoDrogas = usoDrogas;
    }
    public boolean isUsoAlcohol() {
        return this.usoAlcohol;
    }
    
    public void setUsoAlcohol(boolean usoAlcohol) {
        this.usoAlcohol = usoAlcohol;
    }
    public boolean isFumador() {
        return this.fumador;
    }
    
    public void setFumador(boolean fumador) {
        this.fumador = fumador;
    }
    public Set getCirugiases() {
        return this.cirugiases;
    }
    
    public void setCirugiases(Set cirugiases) {
        this.cirugiases = cirugiases;
    }
    public Set getEnfermedadesCronicases() {
        return this.enfermedadesCronicases;
    }
    
    public void setEnfermedadesCronicases(Set enfermedadesCronicases) {
        this.enfermedadesCronicases = enfermedadesCronicases;
    }
    public Set getAlergiases() {
        return this.alergiases;
    }
    
    public void setAlergiases(Set alergiases) {
        this.alergiases = alergiases;
    }
    public Set getMedicacions() {
        return this.medicacions;
    }
    
    public void setMedicacions(Set medicacions) {
        this.medicacions = medicacions;
    }
    public Set getDiscapacidadeses() {
        return this.discapacidadeses;
    }
    
    public void setDiscapacidadeses(Set discapacidadeses) {
        this.discapacidadeses = discapacidadeses;
    }




}


