package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DatosPersonales generated by hbm2java
 */
public class DatosPersonales  implements java.io.Serializable {


     private Long id;
     private Pacientes pacientes;
     private String estadoCivil;
     private String curp;
     private String sexo;
     private Date fechaNacimiento;
     private String edad;
     private String peso;
     private String altura;
     private String talla;
     private String correo;
     private String facebook;

    public DatosPersonales() {
    }

	
    public DatosPersonales(Pacientes pacientes, String estadoCivil, String curp, String sexo, Date fechaNacimiento, String edad) {
        this.pacientes = pacientes;
        this.estadoCivil = estadoCivil;
        this.curp = curp;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
        this.edad = edad;
    }
    public DatosPersonales(Pacientes pacientes, String estadoCivil, String curp, String sexo, Date fechaNacimiento, String edad, String peso, String altura, String talla, String correo, String facebook) {
       this.pacientes = pacientes;
       this.estadoCivil = estadoCivil;
       this.curp = curp;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.edad = edad;
       this.peso = peso;
       this.altura = altura;
       this.talla = talla;
       this.correo = correo;
       this.facebook = facebook;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }
    public String getAltura() {
        return this.altura;
    }
    
    public void setAltura(String altura) {
        this.altura = altura;
    }
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }




}


