package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1


import com.hibernate.model.DatosClinicos;
import java.util.Date;

/**
 * EnfermedadesCronicas generated by hbm2java
 */
public class EnfermedadesCronicas  implements java.io.Serializable {


     private Long id;
     private DatosClinicos datosClinicos;
     private String nombre;
     private String tipo;
     private Date incioEnfermedad;

    public EnfermedadesCronicas() {
    }

	
    public EnfermedadesCronicas(DatosClinicos datosClinicos, String nombre, String tipo) {
        this.datosClinicos = datosClinicos;
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public EnfermedadesCronicas(DatosClinicos datosClinicos, String nombre, String tipo, Date incioEnfermedad) {
       this.datosClinicos = datosClinicos;
       this.nombre = nombre;
       this.tipo = tipo;
       this.incioEnfermedad = incioEnfermedad;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public DatosClinicos getDatosClinicos() {
        return this.datosClinicos;
    }
    
    public void setDatosClinicos(DatosClinicos datosClinicos) {
        this.datosClinicos = datosClinicos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getIncioEnfermedad() {
        return this.incioEnfermedad;
    }
    
    public void setIncioEnfermedad(Date incioEnfermedad) {
        this.incioEnfermedad = incioEnfermedad;
    }




}


