package com.hibernate.model;
// Generated 15-mar-2015 22:58:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidades generated by hbm2java
 */
public class Especialidades  implements java.io.Serializable {


     private int noEspecilidad;
     private String nombreEspecialidad;
     private Set especialidadesHasHospitaleses = new HashSet(0);

    public Especialidades() {
    }

	
    public Especialidades(int noEspecilidad) {
        this.noEspecilidad = noEspecilidad;
    }
    public Especialidades(int noEspecilidad, String nombreEspecialidad, Set especialidadesHasHospitaleses) {
       this.noEspecilidad = noEspecilidad;
       this.nombreEspecialidad = nombreEspecialidad;
       this.especialidadesHasHospitaleses = especialidadesHasHospitaleses;
    }
   
    public int getNoEspecilidad() {
        return this.noEspecilidad;
    }
    
    public void setNoEspecilidad(int noEspecilidad) {
        this.noEspecilidad = noEspecilidad;
    }
    public String getNombreEspecialidad() {
        return this.nombreEspecialidad;
    }
    
    public void setNombreEspecialidad(String nombreEspecialidad) {
        this.nombreEspecialidad = nombreEspecialidad;
    }
    public Set getEspecialidadesHasHospitaleses() {
        return this.especialidadesHasHospitaleses;
    }
    
    public void setEspecialidadesHasHospitaleses(Set especialidadesHasHospitaleses) {
        this.especialidadesHasHospitaleses = especialidadesHasHospitaleses;
    }




}


