package com.hibernate.model;
// Generated 15-mar-2015 22:58:34 by Hibernate Tools 4.3.1



/**
 * EspecialidadesHasHospitales generated by hbm2java
 */
public class EspecialidadesHasHospitales  implements java.io.Serializable {


     private Integer idEspecialidadesHasHospitales;
     private Especialidades especialidades;
     private Hospitales hospitales;

    public EspecialidadesHasHospitales() {
    }

    public EspecialidadesHasHospitales(Especialidades especialidades, Hospitales hospitales) {
       this.especialidades = especialidades;
       this.hospitales = hospitales;
    }
   
    public Integer getIdEspecialidadesHasHospitales() {
        return this.idEspecialidadesHasHospitales;
    }
    
    public void setIdEspecialidadesHasHospitales(Integer idEspecialidadesHasHospitales) {
        this.idEspecialidadesHasHospitales = idEspecialidadesHasHospitales;
    }
    public Especialidades getEspecialidades() {
        return this.especialidades;
    }
    
    public void setEspecialidades(Especialidades especialidades) {
        this.especialidades = especialidades;
    }
    public Hospitales getHospitales() {
        return this.hospitales;
    }
    
    public void setHospitales(Hospitales hospitales) {
        this.hospitales = hospitales;
    }




}


