package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hospitales generated by hbm2java
 */
public class Hospitales  implements java.io.Serializable {


     private String codigoHospital;
     private Usuarios usuarios;
     private String nombre;
     private String telefono;
     private String lada;
     private String EMail;
     private Set domicilioHospitaleses = new HashSet(0);
     private Set peticionesSalienteses = new HashSet(0);
     private Set directivos = new HashSet(0);
     private Set especialidadeses = new HashSet(0);
     private Set peticionesEntranteses = new HashSet(0);
     private Set pacienteses = new HashSet(0);

    public Hospitales() {
    }

	
    public Hospitales(String codigoHospital, Usuarios usuarios, String nombre, String telefono, String lada, String EMail) {
        this.codigoHospital = codigoHospital;
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.telefono = telefono;
        this.lada = lada;
        this.EMail = EMail;
    }
    public Hospitales(String codigoHospital, Usuarios usuarios, String nombre, String telefono, String lada, String EMail, Set domicilioHospitaleses, Set peticionesSalienteses, Set directivos, Set especialidadeses, Set peticionesEntranteses, Set pacienteses) {
       this.codigoHospital = codigoHospital;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.telefono = telefono;
       this.lada = lada;
       this.EMail = EMail;
       this.domicilioHospitaleses = domicilioHospitaleses;
       this.peticionesSalienteses = peticionesSalienteses;
       this.directivos = directivos;
       this.especialidadeses = especialidadeses;
       this.peticionesEntranteses = peticionesEntranteses;
       this.pacienteses = pacienteses;
    }
   
    public String getCodigoHospital() {
        return this.codigoHospital;
    }
    
    public void setCodigoHospital(String codigoHospital) {
        this.codigoHospital = codigoHospital;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getLada() {
        return this.lada;
    }
    
    public void setLada(String lada) {
        this.lada = lada;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public Set getDomicilioHospitaleses() {
        return this.domicilioHospitaleses;
    }
    
    public void setDomicilioHospitaleses(Set domicilioHospitaleses) {
        this.domicilioHospitaleses = domicilioHospitaleses;
    }
    public Set getPeticionesSalienteses() {
        return this.peticionesSalienteses;
    }
    
    public void setPeticionesSalienteses(Set peticionesSalienteses) {
        this.peticionesSalienteses = peticionesSalienteses;
    }
    public Set getDirectivos() {
        return this.directivos;
    }
    
    public void setDirectivos(Set directivos) {
        this.directivos = directivos;
    }
    public Set getEspecialidadeses() {
        return this.especialidadeses;
    }
    
    public void setEspecialidadeses(Set especialidadeses) {
        this.especialidadeses = especialidadeses;
    }
    public Set getPeticionesEntranteses() {
        return this.peticionesEntranteses;
    }
    
    public void setPeticionesEntranteses(Set peticionesEntranteses) {
        this.peticionesEntranteses = peticionesEntranteses;
    }
    public Set getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set pacienteses) {
        this.pacienteses = pacienteses;
    }




}


