package com.hibernate.model;
// Generated 15-mar-2015 22:58:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hospitales generated by hbm2java
 */
public class Hospitales  implements java.io.Serializable {


     private int codigoHospital;
     private Usuarios usuarios;
     private String nombre;
     private String telefono;
     private String lada;
     private String EMail;
     private Set domicilioHospitaleses = new HashSet(0);
     private Set pacienteses = new HashSet(0);
     private Set especialidadesHasHospitaleses = new HashSet(0);
     private Set directivos = new HashSet(0);

    public Hospitales() {
    }

	
    public Hospitales(int codigoHospital, Usuarios usuarios, String nombre, String telefono, String lada, String EMail) {
        this.codigoHospital = codigoHospital;
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.telefono = telefono;
        this.lada = lada;
        this.EMail = EMail;
    }
    public Hospitales(int codigoHospital, Usuarios usuarios, String nombre, String telefono, String lada, String EMail, Set domicilioHospitaleses, Set pacienteses, Set especialidadesHasHospitaleses, Set directivos) {
       this.codigoHospital = codigoHospital;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.telefono = telefono;
       this.lada = lada;
       this.EMail = EMail;
       this.domicilioHospitaleses = domicilioHospitaleses;
       this.pacienteses = pacienteses;
       this.especialidadesHasHospitaleses = especialidadesHasHospitaleses;
       this.directivos = directivos;
    }
   
    public int getCodigoHospital() {
        return this.codigoHospital;
    }
    
    public void setCodigoHospital(int codigoHospital) {
        this.codigoHospital = codigoHospital;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getLada() {
        return this.lada;
    }
    
    public void setLada(String lada) {
        this.lada = lada;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public Set getDomicilioHospitaleses() {
        return this.domicilioHospitaleses;
    }
    
    public void setDomicilioHospitaleses(Set domicilioHospitaleses) {
        this.domicilioHospitaleses = domicilioHospitaleses;
    }
    public Set getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set pacienteses) {
        this.pacienteses = pacienteses;
    }
    public Set getEspecialidadesHasHospitaleses() {
        return this.especialidadesHasHospitaleses;
    }
    
    public void setEspecialidadesHasHospitaleses(Set especialidadesHasHospitaleses) {
        this.especialidadesHasHospitaleses = especialidadesHasHospitaleses;
    }
    public Set getDirectivos() {
        return this.directivos;
    }
    
    public void setDirectivos(Set directivos) {
        this.directivos = directivos;
    }




}


