package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1

import com.hibernate.model.DatosClinicos;




/**
 * Medicacion generated by hbm2java
 */
public class Medicacion  implements java.io.Serializable {


     private Long id;
     private DatosClinicos datosClinicos;
     private String nombreMedicamento;
     private String frecuencia;

    public Medicacion() {
    }

	
    public Medicacion(DatosClinicos datosClinicos) {
        this.datosClinicos = datosClinicos;
    }
    public Medicacion(DatosClinicos datosClinicos, String nombreMedicamento, String frecuencia) {
       this.datosClinicos = datosClinicos;
       this.nombreMedicamento = nombreMedicamento;
       this.frecuencia = frecuencia;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public DatosClinicos getDatosClinicos() {
        return this.datosClinicos;
    }
    
    public void setDatosClinicos(DatosClinicos datosClinicos) {
        this.datosClinicos = datosClinicos;
    }
    public String getNombreMedicamento() {
        return this.nombreMedicamento;
    }
    
    public void setNombreMedicamento(String nombreMedicamento) {
        this.nombreMedicamento = nombreMedicamento;
    }
    public String getFrecuencia() {
        return this.frecuencia;
    }
    
    public void setFrecuencia(String frecuencia) {
        this.frecuencia = frecuencia;
    }




}


