package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private String nss;
     private Hospitales hospitales;
     private Usuarios usuarios;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String unidadMedica;
     private String noConsultorio;
     private byte[] imagen;
     private Set domicilioPacienteses = new HashSet(0);
     private Set peticionesEntranteses = new HashSet(0);
     private Set peticionesSalienteses = new HashSet(0);
     private Set telefonosPacienteses = new HashSet(0);
     private Set datosClinicoses = new HashSet(0);
     private Set datosPersonaleses = new HashSet(0);
     private Set contactoses = new HashSet(0);

    public Pacientes() {
    }

	
    public Pacientes(String nss, Hospitales hospitales, Usuarios usuarios, String nombre, String apellidoPaterno, String apellidoMaterno) {
        this.nss = nss;
        this.hospitales = hospitales;
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
    }
    public Pacientes(String nss, Hospitales hospitales, Usuarios usuarios, String nombre, String apellidoPaterno, String apellidoMaterno, String unidadMedica, String noConsultorio, byte[] imagen, Set domicilioPacienteses, Set peticionesEntranteses, Set peticionesSalienteses, Set telefonosPacienteses, Set datosClinicoses, Set datosPersonaleses, Set contactoses) {
       this.nss = nss;
       this.hospitales = hospitales;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.unidadMedica = unidadMedica;
       this.noConsultorio = noConsultorio;
       this.imagen = imagen;
       this.domicilioPacienteses = domicilioPacienteses;
       this.peticionesEntranteses = peticionesEntranteses;
       this.peticionesSalienteses = peticionesSalienteses;
       this.telefonosPacienteses = telefonosPacienteses;
       this.datosClinicoses = datosClinicoses;
       this.datosPersonaleses = datosPersonaleses;
       this.contactoses = contactoses;
    }
   
    public String getNss() {
        return this.nss;
    }
    
    public void setNss(String nss) {
        this.nss = nss;
    }
    public Hospitales getHospitales() {
        return this.hospitales;
    }
    
    public void setHospitales(Hospitales hospitales) {
        this.hospitales = hospitales;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getUnidadMedica() {
        return this.unidadMedica;
    }
    
    public void setUnidadMedica(String unidadMedica) {
        this.unidadMedica = unidadMedica;
    }
    public String getNoConsultorio() {
        return this.noConsultorio;
    }
    
    public void setNoConsultorio(String noConsultorio) {
        this.noConsultorio = noConsultorio;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set getDomicilioPacienteses() {
        return this.domicilioPacienteses;
    }
    
    public void setDomicilioPacienteses(Set domicilioPacienteses) {
        this.domicilioPacienteses = domicilioPacienteses;
    }
    public Set getPeticionesEntranteses() {
        return this.peticionesEntranteses;
    }
    
    public void setPeticionesEntranteses(Set peticionesEntranteses) {
        this.peticionesEntranteses = peticionesEntranteses;
    }
    public Set getPeticionesSalienteses() {
        return this.peticionesSalienteses;
    }
    
    public void setPeticionesSalienteses(Set peticionesSalienteses) {
        this.peticionesSalienteses = peticionesSalienteses;
    }
    public Set getTelefonosPacienteses() {
        return this.telefonosPacienteses;
    }
    
    public void setTelefonosPacienteses(Set telefonosPacienteses) {
        this.telefonosPacienteses = telefonosPacienteses;
    }
    public Set getDatosClinicoses() {
        return this.datosClinicoses;
    }
    
    public void setDatosClinicoses(Set datosClinicoses) {
        this.datosClinicoses = datosClinicoses;
    }
    public Set getDatosPersonaleses() {
        return this.datosPersonaleses;
    }
    
    public void setDatosPersonaleses(Set datosPersonaleses) {
        this.datosPersonaleses = datosPersonaleses;
    }
    public Set getContactoses() {
        return this.contactoses;
    }
    
    public void setContactoses(Set contactoses) {
        this.contactoses = contactoses;
    }




}


