package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PeticionesEntrantes generated by hbm2java
 */
public class PeticionesEntrantes  implements java.io.Serializable {


     private String idPeticionesEntrantes;
     private Hospitales hospitales;
     private Pacientes pacientes;
     private Date fechaRegistro;
     private String estatus;
     private String latitudPaciente;
     private String longitudPaciente;
     private String prioridad;
     private String comentario;
     /***********ATRIBUTOS PARA EL GRID DATOS DE PACIENTE***************/
     private String nombrePaciente;
     private String apellidoPaciente;
     private Date fechaNacimineto;
     private String nss;

    public PeticionesEntrantes() {
    }

	
    public PeticionesEntrantes(String idPeticionesEntrantes, Hospitales hospitales, Pacientes pacientes, Date fechaRegistro, String estatus, String latitudPaciente, String longitudPaciente, String prioridad) {
        this.idPeticionesEntrantes = idPeticionesEntrantes;
        this.hospitales = hospitales;
        this.pacientes = pacientes;
        this.fechaRegistro = fechaRegistro;
        this.estatus = estatus;
        this.latitudPaciente = latitudPaciente;
        this.longitudPaciente = longitudPaciente;
        this.prioridad = prioridad;
    }
    public PeticionesEntrantes(String idPeticionesEntrantes, Hospitales hospitales, Pacientes pacientes, Date fechaRegistro, String estatus, String latitudPaciente, String longitudPaciente, String prioridad, String comentario) {
       this.idPeticionesEntrantes = idPeticionesEntrantes;
       this.hospitales = hospitales;
       this.pacientes = pacientes;
       this.fechaRegistro = fechaRegistro;
       this.estatus = estatus;
       this.latitudPaciente = latitudPaciente;
       this.longitudPaciente = longitudPaciente;
       this.prioridad = prioridad;
       this.comentario = comentario;
    }
   
    public String getIdPeticionesEntrantes() {
        return this.idPeticionesEntrantes;
    }
    
    public void setIdPeticionesEntrantes(String idPeticionesEntrantes) {
        this.idPeticionesEntrantes = idPeticionesEntrantes;
    }
    public Hospitales getHospitales() {
        return this.hospitales;
    }
    
    public void setHospitales(Hospitales hospitales) {
        this.hospitales = hospitales;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getLatitudPaciente() {
        return this.latitudPaciente;
    }
    
    public void setLatitudPaciente(String latitudPaciente) {
        this.latitudPaciente = latitudPaciente;
    }
    public String getLongitudPaciente() {
        return this.longitudPaciente;
    }
    
    public void setLongitudPaciente(String longitudPaciente) {
        this.longitudPaciente = longitudPaciente;
    }
    public String getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
/*********************GETTERS AND SETTER PARA PACIENTE GRID********************************/
  
    public String getNombrePaciente() {
        return nombrePaciente;
    }

    public void setNombrePaciente(String nombrePaciente) {
        this.nombrePaciente = nombrePaciente;
    }

    public String getApellidoPaciente() {
        return apellidoPaciente;
    }

    public void setApellidoPaciente(String apellidoPaciente) {
        this.apellidoPaciente = apellidoPaciente;
    }

    public Date getFechaNacimineto() {
        return fechaNacimineto;
    }

    public void setFechaNacimineto(Date fechaNacimineto) {
        this.fechaNacimineto = fechaNacimineto;
    }

    public String getNss() {
        return nss;
    }

    public void setNss(String nss) {
        this.nss = nss;
    }


  

}


