package com.hibernate.model;
// Generated 2/06/2015 02:02:20 AM by Hibernate Tools 4.3.1



/**
 * TelefonosPacientes generated by hbm2java
 */
public class TelefonosPacientes  implements java.io.Serializable {


     private Long id;
     private Pacientes pacientes;
     private String numeroTelefono;

    public TelefonosPacientes() {
    }

    public TelefonosPacientes(Pacientes pacientes, String numeroTelefono) {
       this.pacientes = pacientes;
       this.numeroTelefono = numeroTelefono;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public String getNumeroTelefono() {
        return this.numeroTelefono;
    }
    
    public void setNumeroTelefono(String numeroTelefono) {
        this.numeroTelefono = numeroTelefono;
    }




}


