package com.hibernate.model;
// Generated 22-may-2015 20:27:16 by Hibernate Tools 4.3.1



/**
 * TelefonosPacientes generated by hbm2java
 */
public class TelefonosPacientes  implements java.io.Serializable {


     private Long id;
     private Pacientes pacientes;
     private String telefonoFijo;
     private String telefonoParticular;

    public TelefonosPacientes() {
    }

    public TelefonosPacientes(Pacientes pacientes, String telefonoFijo, String telefonoParticular) {
       this.pacientes = pacientes;
       this.telefonoFijo = telefonoFijo;
       this.telefonoParticular = telefonoParticular;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public String getTelefonoParticular() {
        return this.telefonoParticular;
    }
    
    public void setTelefonoParticular(String telefonoParticular) {
        this.telefonoParticular = telefonoParticular;
    }




}


